# Generated by Django 4.2.1 on 2023-05-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasYa', '0002_alter_locacion_numero_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacion',
            name='numero_direccion',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
