# Generated by Django 4.2.1 on 2023-05-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citasYa', '0003_alter_locacion_numero_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacion',
            name='numero_direccion',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='limite_distancia',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rango_edad',
            field=models.CharField(max_length=30),
        ),
    ]
