name: Add TK prefix and label to new issues
on:
  issues:
    types: [opened]
jobs:
  add-tk-prefix-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest TK issue number
        run: |
          last_tk_issue=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X GET "https://api.github.com/repos/${{ github.repository }}/issues?state=all" \
            | jq -r '.[].title | select(. | test("\\[TK-[0-9]+\\]")) | match("\\d+") | .string' \
            | sort -n \
            | tail -n1)
          if [ -z "$last_tk_issue" ]; then
            last_tk_issue=0
          fi
          echo "::set-env name=LAST_TK_ISSUE::$last_tk_issue"
      - name: Add TK prefix to new issue
        run: |
          number=$((${{ env.LAST_TK_ISSUE }} + 1))
          title=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X GET https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            | jq -r '.title')
          if echo "$title" | grep -qEi "(como.*quiero|quiero.*como)"; then
            new_title="$title"
          else
            new_title="[TK-${number}] ${title}"
          fi
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X PATCH https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d "{\"title\":\"${new_title}\"}"
      - name: Add new issue to active project
        if: always()
        run: |
          project_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -X GET https://api.github.com/repos/${{ github.repository }}/projects \
            | jq -r '.[] | select(.name == "Grupo 28 - CitasYa") | .url')
          if [ ! -z "$project_url" ]; then
            project_id=$(echo $project_url | sed 's/.*\/\([0-9]\+\)$/\1/')
            column_url=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -X GET https://api.github.com/projects/${project_id}/columns \
              | jq -r '.[0].url')
            if [ ! -z "$column_url" ]; then
              column_id=$(echo $column_url | sed 's/.*\/\([0-9]\+\)$/\1/')
              curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -X POST https://api.github.com/projects/columns/${column_id}/cards \
                -d "{\"content_id\":${{ github.event.issue.number }},\"content_type\":\"Issue\"}"
            fi
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
