name: Add TK prefix and label to new issues
on:
  issues:
    types: [opened]
jobs:
  add-tk-prefix-and-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add TK prefix to new issue
        uses: peter-evans/add-issue-labels@v1.3.2
        with:
          labels: '[TK-{{ github.event.issue.number }}], 2023'
      - name: Add new issue to active project
        uses: ahmadawais/add-new-issue-to-github-project@v2.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          project_name: "Grupo 28 - CitasYa"
